<?php

/**
 * @file
 * mrc_media.module
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\editor\Entity\Editor;
use Drupal\mrc_media\MrcMediaEntityEmbedDialog;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds Linkit support for the link field in the entity embed dialog.
 */
function mrc_media_form_entity_embed_dialog_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['attributes']['data-entity-embed-display-settings'])) {
    $editor = $form_state->getBuildInfo()['args'][0];
    if ($editor instanceof Editor) {
      \Drupal::classResolver()
        ->getInstanceFromDefinition(MrcMediaEntityEmbedDialog::class)
        ->alterForm($form, $form_state);
    }
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function mrc_media_theme_registry_alter(&$theme_registry) {
  $path = drupal_get_path('module', 'mrc_media') . '/templates';
  $theme_registry['image_formatter']['path'] = $path;
  $theme_registry['entity_embed_container']['path'] = $path;
}

/**
 * Implements hook_entity_embed_alter().
 */
function mrc_media_entity_embed_alter(array &$build, EntityInterface $entity, array &$context) {
  if (!empty($context['data-entity-embed-display-settings']['linkit'])) {
    $linkit_attributes = $context['data-entity-embed-display-settings']['linkit'];
    try {
      $linkit_attributes['href'] = Url::fromUserInput($linkit_attributes['href'])
        ->toString();
    }
    catch (Exception $e) {
      // Nothing to do since the link is a full url.
    }

    $build['entity']['#url'] = $linkit_attributes;
  }
}

/**
 * Implements hook_preprocess_image_formatter().
 */
function mrc_media_preprocess_image_formatter(&$variables) {
  if (!empty($variables['url'])) {
    if ($variables['url'] instanceof Url) {
      $variables['url'] = ['href' => $variables['url']->toString()];
    }
    $variables['url_attributes'] = new Attribute($variables['url']);
  }
}
