<?php

/**
 * @file
 * mrc_visitor.mdoule
 */

use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_field_widget_form_alter().
 */
function mrc_visitor_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  // Change form to be a year range instead of a single year.
  if ($context['items']->getName() == 'field_s_visitor_year_visited') {
    foreach ($element['value']['#options'] as &$option) {
      $option = $option - 1 . ' - ' . $option;
    }

    krsort($element['value']['#options']);
  }
}
