<?php

/**
 * @file
 * mrc_helper.module
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function mrc_helper_taxonomy_term_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->bundle() == 'mrc_event_series' && $display->getMode() == 'default' && !empty($build['field_mrc_event_series_name'])) {
    $build['name'] = $build['field_mrc_event_series_name'];
    unset($build['field_mrc_event_series_name']);
  }
}
