<?php

/**
 * @file
 * mrc_ds_blocks.module
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\Entity\EntityViewDisplay;
use Drupal\field_ui\Form\EntityDisplayFormBase;
use Drupal\Core\Entity\EntityDisplayBase;
use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Component\Utility\Html;
use Drupal\Core\Entity\EntityInterface;
use Drupal\mrc_ds_blocks\MrcDsBlocks;

/**
 * Implements hook_entity_view_alter().
 */
function mrc_ds_blocks_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  /** @var \Drupal\Core\Block\BlockManager $block_manager */
  $block_manager = \Drupal::service('plugin.manager.block');

  $entity_type = $display->getTargetEntityTypeId();
  $bundle = $entity->bundle();
  $mode = $display->getMode();

  // Get all blocks for the entity with the specified view mode.
  $blocks = mrc_ds_blocks_get_blocks($entity_type, $bundle, 'view', $mode);

  foreach ($blocks as $block_id => $block) {
    // Skip the block if it has been deleted or is missing somehow.
    if (!$block_manager->hasDefinition($block_id)) {
      continue;
    }

    // Create the block and add it to the the entity.
    $block_instance = $block_manager->createInstance($block_id, $block->config);
    $build[$block_id] = $block_instance->build();
    $build[$block_id]['#weight'] = $block->weight;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alot of this was taken from field_group_field_ui_display_form_alter().
 */
function mrc_ds_blocks_form_entity_view_display_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Only start altering the form if we need to.
  if (empty($form['#fields']) && empty($form['#extra'])) {
    return;
  }

  $callback_object = $form_state->getBuildInfo()['callback_object'];
  if (!$callback_object instanceof EntityDisplayFormBase) {
    throw new InvalidArgumentException('Unkown callback object.');
  }

  $display = $callback_object->getEntity();

  $params = mrc_ds_blocks_field_ui_form_params($form, $display);

  $table = &$form['fields'];
  /** @var \Drupal\Core\Block\BlockManager $block_manager */
  $block_manager = \Drupal::service('plugin.manager.block');
  $blocks = $block_manager->getDefinitions();

  $form['#mrc_ds_blocks'] = array_keys($params->blocks);

  $base_button = [
    '#submit' => [
      [
        $form_state->getBuildInfo()['callback_object'],
        'multistepSubmit',
      ],
    ],
    '#ajax' => [
      'callback' => [
        $form_state->getBuildInfo()['callback_object'],
        'multistepAjax',
      ],
      'wrapper' => 'field-display-overview-wrapper',
      'effect' => 'fade',
    ],
  ];

  // Go through each block and add it to the table.
  foreach ($params->blocks as $block_id => $block) {

    // Skip if the block doesn't exist.
    if (!$block_manager->hasDefinition($block_id)) {
      continue;
    }

    if ($form_state->get('plugin_settings_update') == $block_id) {
      mrc_ds_blocks_form_update_block($form, $form_state);
    }

    $base_button['#field_name'] = $block_id;
    $block_row = [
      '#attributes' => [
        'class' => ['draggable', 'tabledrag-leaf'],
        'id' => $block_id,
      ],
      '#row_type' => 'field',
      '#region_callback' => $params->region_callback,
      '#js_settings' => ['rowHandler' => 'field'],
      'human_name' => [
        '#markup' => Html::escape($blocks[$block_id]['admin_label']),
        '#prefix' => '<span class="block-label">',
        '#suffix' => '</span>',
      ],
      'weight' => [
        '#type' => 'textfield',
        '#default_value' => $block->weight,
        '#size' => 3,
        '#attributes' => ['class' => ['field-weight']],
      ],
      'parent_wrapper' => [
        'parent' => [
          '#type' => 'select',
          '#options' => [],
          '#empty_value' => '',
          '#default_value' => isset($params->parents[$block_id]) ? $params->parents[$block_id] : '',
          '#attributes' => ['class' => ['field-parent']],
          '#parents' => ['fields', $block_id, 'parent'],
        ],
        'hidden_name' => [
          '#type' => 'hidden',
          '#default_value' => $block_id,
          '#attributes' => ['class' => ['field-name']],
        ],
      ],
      'spacer' => [
        '#markup' => '&nbsp;',
      ],
      'format' => [
        '#markup' => '&nbsp;',
      ],
      'settings_summary' => ['#markup' => ''],
    ];

    if ($form_state->get('plugin_settings_edit') == $block_id) {
      $block_row['settings_edit']['#cell_attributes'] = ['colspan' => 2];
      $block_row['format']['format_settings'] = [
        '#type' => 'container',
        '#attributes' => ['class' => ['field-plugin-settings-edit-form']],
        '#array_parents' => ['fields', $block_id, 'settings_edit_form'],
        '#weight' => -5,
        // Create a settings form where hooks can pick in.
        'settings' => mrc_ds_blocks_block_form($form_state, $block_id, $block->config),
        'actions' => [
          '#type' => 'actions',
          'save_settings' => $base_button + [
              '#type' => 'submit',
              '#name' => $block_id . '_plugin_settings_update',
              '#value' => t('Update'),
              '#op' => 'update',
            ],
          'cancel_settings' => $base_button + [
              '#type' => 'submit',
              '#name' => $block_id . '_plugin_settings_cancel',
              '#value' => t('Cancel'),
              '#op' => 'cancel',
              // Do not check errors for the 'Cancel' button.
              '#limit_validation_errors' => [],
            ],
        ],
      ];
      $block_row['#attributes']['class'][] = 'field-formatter-settings-editing';
      $block_row['format']['type']['#attributes']['class'] = ['visually-hidden'];
    }
    else {
      $block_row['settings_edit'] = [
        '#type' => 'image_button',
        '#name' => $block_id . '_block_settings_edit',
        '#src' => 'core/misc/icons/787878/cog.svg',
        '#attributes' => [
          'class' => ['field-plugin-settings-edit'],
          'alt' => t('Edit'),
        ],
        '#op' => 'edit',
        // Do not check errors for the 'Edit' button, but make sure we get
        // the value of the 'plugin type' select.
        '#limit_validation_errors' => [['fields', $block_id, 'type']],
        '#prefix' => '<div class="field-plugin-settings-edit-wrapper">',
        '#suffix' => '</div>',
      ];

      $block_row['settings_edit'] += $base_button;

      // Add the delete button.
      $block->blockId = $block_id;
      $delete_route = MrcDsBlocks::getDeleteRoute($block);
      $block_row['settings_edit']['#suffix'] .= Drupal::l(t('delete'), $delete_route);
    }

    $table[$block_id] = $block_row;
  }

  array_unshift($form['actions']['submit']['#submit'], 'mrc_ds_blocks_field_overview_submit');
}

/**
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $block_id
 * @param array $config
 *
 * @return array
 */
function mrc_ds_blocks_block_form(FormStateInterface $form_state, $block_id, $config = []) {
  $form = [];
  $block_manager = \Drupal::service('plugin.manager.block');
  $block = $block_manager->createInstance($block_id, $config);
  $form = $block->buildConfigurationForm($form, $form_state);
  return $form;
}

/**
 * @param string $block_id
 * @param \stdClass $parameters
 * @param array $settings
 */
function mrc_ds_blocks_form_update_block(array $form, FormStateInterface $form_state) {

  $callback_object = $form_state->getBuildInfo()['callback_object'];
  if (!$callback_object instanceof EntityDisplayFormBase) {
    throw new InvalidArgumentException('Unkown callback object.');
  }

  $display = $callback_object->getEntity();

  $parameters = mrc_ds_blocks_field_ui_form_params($form, $display);
  $block_id = $form_state->get('plugin_settings_update');
  $blocks = $parameters->blocks;
  $config = &$blocks[$block_id]->config;

  $form_values = $form_state->getValue([
    'fields',
    $block_id,
    'format',
    'format_settings',
    'settings',
  ]);

  if (!empty($form_values)) {
    mrc_ds_blocks_match_config($config, $form_values);
    mrc_ds_blocks_save($blocks[$block_id]);
  }
}

/**
 * @param $config
 * @param $form_values
 */
function mrc_ds_blocks_match_config(&$config, $form_values) {
  if (!is_array($config)) {
    return;
  }

  foreach ($config as $key => &$value) {
    if (is_array($value)) {
      mrc_ds_blocks_match_config($value, $form_values);
      continue;
    }
    $value = mrc_ds_blocks_find_value($key, $form_values);
  }
}

/**
 * Find a nested value
 *
 * @param $key
 * @param array $values
 *
 * @return mixed|null
 */
function mrc_ds_blocks_find_value($key, array $values) {
  if (isset($values[$key])) {
    return $values[$key];
  }
  foreach ($values as $value) {
    if (is_array($value)) {
      return mrc_ds_blocks_find_value($key, $value);
    }
  }
  return NULL;
}

/**
 * Submit handler for the overview screens.
 *
 * @param array $form
 *   The complete form.
 * @param FormStateInterface $form_state
 *   The state of the form.
 */
function mrc_ds_blocks_field_overview_submit($form, FormStateInterface $form_state) {
  $form_values = $form_state->getValue('fields');

  /** @var \Drupal\Core\Entity\EntityDisplayBase $display */
  $display = $form['#context'];

  $entity_type = $display->get('targetEntityType');
  $bundle = $display->get('bundle');
  $mode = $display->get('mode');
  $context = mrc_ds_blocks_get_context_from_display($display);

  // Update existing blocks.
  $blocks = mrc_ds_blocks_get_blocks($entity_type, $bundle, $context, $mode);

  foreach ($form['#mrc_ds_blocks'] as $block_id) {

    // Only save updated blocks.
    if (!isset($blocks[$block_id])) {
      continue;
    }

    $block = $blocks[$block_id];
    $block->parent_name = $form_values[$block_id]['parent'];
    $block->weight = $form_values[$block_id]['weight'];

    /** @var \Drupal\Core\Entity\EntityFormInterface $entity_form */
    $entity_form = $form_state->getFormObject();

    /** @var \Drupal\Core\Entity\Display\EntityDisplayInterface $display */
    $display = $entity_form->getEntity();

    $block->blockId = $block_id;
    mrc_ds_blocks_save($block, $display);
  }
}

/**
 * Saves a block configuration.
 *
 * @param \stdClass $block
 *   A block definition.
 * @param \Drupal\Core\Entity\Display\EntityDisplayInterface $display
 *   The display to update if known.
 *
 * @return \Drupal\Core\Entity\Display\EntityDisplayInterface|NULL
 *   The updated entity display.
 */
function mrc_ds_blocks_save($block, $display = NULL) {
  if ($display === NULL) {
    $display = EntityViewDisplay::load($block->entity_type . '.' . $block->bundle . '.' . $block->mode);
  }

  // If no display was found. It doesn't exist yet, create it.
  if (!isset($display)) {
    $display = EntityViewDisplay::create([
      'targetEntityType' => $block->entity_type,
      'bundle' => $block->bundle,
      'mode' => $block->mode,
    ])->setStatus(TRUE);
  }

  if (isset($display)) {
    $data = (array) $block;
    unset($data['blockId'], $data['entity_type'], $data['bundle'], $data['mode'], $data['form'], $data['context']);

    // Merge old data if there is any.
    $old_data = $display->getThirdPartySetting('mrc_ds_blocks', $block->blockId, $data);
    $data = ((array) $block) + $old_data;
    $display->setThirdPartySetting('mrc_ds_blocks', $block->blockId, $data);
    $display->save();
  }

  return $display;
}

/**
 * Helper function to get the form parameters to use while
 * building the fields and display overview form.
 *
 * @param $form
 *
 * @param \Drupal\Core\Entity\EntityDisplayBase $display
 *
 * @return \stdClass
 */
function mrc_ds_blocks_field_ui_form_params($form, EntityDisplayBase $display) {

  $params = new stdClass();
  $params->entity_type = $display->getTargetEntityTypeId();
  $params->bundle = $display->getTargetBundle();
  $params->region_callback = '';
  $params->mode = $display->getMode();
  $params->context = mrc_ds_blocks_get_context_from_display($display);

  $params->blocks = [];
  $params->blocks = mrc_ds_blocks_get_blocks($params->entity_type, $params->bundle, $params->context, $params->mode);

  // Gather parenting data.
  $params->parents = [];
  return $params;
}

/**
 * Loads a block config.
 *
 * @param $block_id
 *   The block key.
 * @param $entity_type
 *   The name of the entity.
 * @param $bundle
 *   The name of the bundle.
 * @param $context
 *   The context of the view mode (form or view)
 * @param $mode
 *   The view mode to load.
 *
 * @return null|object
 */
function mrc_ds_blocks_load_block($block_id, $entity_type, $bundle, $context, $mode) {
  $blocks = mrc_ds_blocks_get_blocks($entity_type, $bundle, $context, $mode);
  if (isset($blocks[$block_id])) {
    return $blocks[$block_id];
  }
  return NULL;
}

/**
 * Helper function to get context from entity display.
 *
 * @param \Drupal\Core\Entity\EntityDisplayBase $display
 *
 * @return string
 */
function mrc_ds_blocks_get_context_from_display(EntityDisplayBase $display) {
  if ($display instanceof EntityFormDisplayInterface) {
    return 'form';
  }
  elseif ($display instanceof EntityViewDisplayInterface) {
    return 'view';
  }

  throw new LogicException('Unknown display object.');
}

/**
 * Get all blocks on a specific display.
 *
 * @param $entity_type
 *   The name of the entity.
 * @param $bundle
 *   The name of the bundle.
 * @param $context
 *   The context of the view mode (form or view)
 * @param $mode
 *   The view mode.
 *
 * @return array
 *   Array of blocks.
 */
function mrc_ds_blocks_get_blocks($entity_type, $bundle, $context, $mode) {
  // We only care about view modes.
  if ($context != 'view') {
    return [];
  }

  $display = EntityViewDisplay::load($entity_type . '.' . $bundle . '.' . $mode);
  if (!$display) {
    return [];
  }
  $data = $display->getThirdPartySettings('mrc_ds_blocks');


  $blocks = [];
  if (isset($data) && is_array($data)) {
    foreach ($data as $block_id => $definition) {
      $definition += [
        'entity_type' => $entity_type,
        'bundle' => $bundle,
        'context' => $context,
        'mode' => $mode,
      ];
      $blocks[$block_id] = (object) $definition;
    }
  }
  return $blocks;
}

/**
 * Deletes a block configuration from a view mode.
 *
 * @param \stdClass $block
 *   The block to remove.
 */
function mrc_ds_blocks_delete_block($block) {
  $display = EntityViewDisplay::load($block->entity_type . '.' . $block->bundle . '.' . $block->mode);

  /**
   * @var $display \Drupal\Core\Entity\Display\EntityDisplayInterface
   */
  if (isset($display)) {
    $display->unsetThirdPartySetting('mrc_ds_blocks', $block->blockId);
    $display->save();
  }
}
